Repository Muhammad-Anfaal/smart-parking-system, pull requests merged in 2024-03, with the labels that each got.

#5 pulling data from main to my-branch-1
  backend/app.js
  backend/controllers/carController.js
  backend/controllers/userController.js
  backend/db.js
  backend/models/Admin.js
  backend/models/Car.js
  backend/models/Subscription.js
  backend/package-lock.json
  backend/package.json
  backend/routes/Car_routes.js
  backend/routes/User_routes.js
Labels: enhancement, help wanted

#12 parking area registration module has been made
  backend/app.js
  backend/controllers/parkingAreaController.js
  backend/db.js
  backend/models/ParkingArea.js
  backend/models/User.js
  backend/routes/ParkingArea_routes.js
Labels: enhancement, Fixed

#11 Update db.js file
  backend/db.js
Labels: enhancement, question, Fixed

#15 update regex of car's number-plate
  backend/models/Car.js
Labels: enhancement, Fixed

#17 created admin module
  backend/app.js
  backend/controllers/adminController.js
  backend/db.js
  backend/models/Admin.js
  backend/routes/Admin_routes.js
  backend/routes/User_routes.js
Labels: enhancement

#19 applied_modifications
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/Admin/approve_area.dart
  frontend/smart_parking_system/lib/screens/payment_page.dart
  frontend/smart_parking_system/lib/screens/select_time.dart
  frontend/smart_parking_system/lib/screens/subscription.dart
  frontend/smart_parking_system/pubspec.lock
  frontend/smart_parking_system/pubspec.yaml
Labels: enhancement, Fixed

#21 Backend Integration with Frontend
  backend/app.js
  backend/controllers/userController.js
  backend/models/User.js
  backend/routes/User_routes.js
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/Admin/home_page_admin.dart
  frontend/smart_parking_system/lib/screens/home_page_user.dart
  frontend/smart_parking_system/lib/screens/log_in.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/pin_code.dart
  frontend/smart_parking_system/lib/screens/sign_up.dart
  frontend/smart_parking_system/pubspec.lock
Labels: enhancement, Fixed

#22 Backend integration frontend
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/pubspec.lock
Labels: enhancement, Fixed

#23 Modifications on car registration page, subscription page
  frontend/smart_parking_system/lib/screens/car_registration.dart
  frontend/smart_parking_system/lib/screens/home_page_user.dart
  frontend/smart_parking_system/lib/screens/subscription.dart
Labels: bug, enhancement, Fixed

#24 Editied Register Area
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/payment_page.dart
  frontend/smart_parking_system/lib/screens/subscription.dart
Labels: enhancement, Fixed

#25 updated frontend
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/reservation_page.dart
Labels: Fixed

#26 insert functionality of image on sign-up page
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/sign_up.dart
Labels: bug, enhancement, Fixed

#27 changes in backend and add feedback module.
  backend/controllers/adminController.js
  backend/controllers/carController.js
  backend/controllers/parkingAreaController.js
  backend/controllers/subscriptionController.js
  backend/controllers/userController.js
  backend/db.js
  backend/models/Feedback.js
  backend/routes/Admin_routes.js
  backend/routes/Car_routes.js
  backend/routes/ParkingArea_routes.js
  backend/routes/Subscription_routes.js
  backend/routes/User_routes.js
Labels: enhancement, Fixed

#28 Backend integration frontend
  backend/controllers/userController.js
  backend/models/User.js
  frontend/smart_parking_system/lib/screens/log_in.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/reservation_page.dart
  frontend/smart_parking_system/lib/screens/sign_up.dart
Labels: bug, enhancement

#29 Shared Preferences Addition
  frontend/smart_parking_system/lib/main.dart
  frontend/smart_parking_system/lib/screens/Admin/home_page_admin.dart
  frontend/smart_parking_system/lib/screens/home_page_user.dart
  frontend/smart_parking_system/lib/screens/log_in.dart
  frontend/smart_parking_system/lib/screens/owner/extend_area.dart
  frontend/smart_parking_system/lib/screens/owner/home_page_owner.dart
  frontend/smart_parking_system/lib/screens/payment_page.dart
  frontend/smart_parking_system/lib/screens/select_time.dart
Labels: enhancement, help wanted, question, Fixed

#30 Backend integration frontend
  backend/controllers/userController.js
  backend/models/Feedback.js
  backend/models/User.js
  backend/routes/User_routes.js
  frontend/smart_parking_system/assets/images/profile.png
  frontend/smart_parking_system/lib/screens/Admin/home_page_admin.dart
  frontend/smart_parking_system/lib/screens/home_page_user.dart
  frontend/smart_parking_system/lib/screens/owner/home_page_owner.dart
  frontend/smart_parking_system/lib/screens/owner/register_parking_area.dart
  frontend/smart_parking_system/lib/screens/pin_code.dart
  frontend/smart_parking_system/lib/screens/reservation_page.dart
  frontend/smart_parking_system/lib/screens/sign_up.dart
  frontend/smart_parking_system/pubspec.lock
  frontend/smart_parking_system/pubspec.yaml
Labels: enhancement, Fixed
